spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
          temp:
            use_jdbc_metadata_defaults: false
        order_inserts: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/heroes_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

    hikari:
      idle-timeout: 10000 # 10 seg, tiempo máximo en que una conexión del pool puede estar inactiva
      maximum-pool-size: 5
      connectionTimeout: 60000 # 60 seg, tiempo de espera para una nueva conexión antes de lanzar el error de conexión
      maxLifetime: 1800000 # 30 minutos, tiempo máximo que puede estar activa una conexión del pool
