#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        order_inserts: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        jdbc:
#          batch_size: 50
#          lob:
#            non_contextual_creation: true
#        temp:
#          use_jdbc_metadata_defaults: false
#
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: ${URL_DB}
#    username: ${USERNAME_DB}
#    password: ${PASSWORD_DB}
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      idle-timeout: 10000 # 10 seg, tiempo máximo en que una conexión del pool puede estar inactiva
#      maximum-pool-size: 5
#      connectionTimeout: 60000 # 60 seg, tiempo de espera para una nueva conexión antes de lanzar el error de conexión
#      maxLifetime: 1800000 # 30 minutos, tiempo máximo que puede estar activa una conexión del pool